main: com.gmail.markushygedombrowski.HLUtils
version: "1.0"
name: HLUtils
softdepend:  [Vault,WorldGuard,WorldEdit,HLWarp]
commands:
  hlgamemode:
    aliases: ["hlgm"]
    description: "gamemode"
  hlutilsreload:
    description: "reload"
  hltp:
    aliases: ["hltphere"]
  st:
    description: "staff chat"
  blockitem:
    description: "blocks items"
  sendmessage:
    description: "send message"
  iteminfo:
    description: "item info"
  ecd:
    description: "enderchest"
  list:
    description: "list"
