main: com.gmail.markushygedombrowski.HLUtils
version: "1.0"
name: HLUtils
softdepend:  [Vault,WorldGuard,WorldEdit]
commands:
  hlgamemode:
    aliases: ["hlgm"]
    description: "gamemode"
  hlutilsreload:
    description: "reload"
  hlwarp:
    aliases: ["hlsetwarp"]
    description: "HLWarp System"
  hltp:
    aliases: ["hltphere"]
  st:
    description: "staff chat"
  blockitem:
    description: "blocks items"